[project]
name = "project"
version = "0.1.0"
dependencies = []

[tool.setuptools]
packages = ["src"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"